#!/usr/bin/env bash
######################################################################
# .what = run repo tests with turtle vibes summary and log capture
#
# .why  = enables lint enforcement in hooks:
#         - exit code 2 forces brain to address defects
#         - summary output saves tokens (details in log file)
#         - consistent vibes across mechanic skills
#
# usage:
#   git.repo.test.sh --what lint                    # run lint check
#   git.repo.test.sh --what lint --when hook.onStop # context hint (for future use)
#
# guarantee:
#   - logs raw output to .log/role=mechanic/skill=git.repo.test/
#   - findserts .gitignore in log directory
#   - exit 0 = passed, exit 1 = malfunction, exit 2 = constraint
######################################################################
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# source shared output operations
CLAUDE_TOOLS_DIR="$SCRIPT_DIR/../claude.tools"
source "$CLAUDE_TOOLS_DIR/output.sh"

######################################################################
# constants
######################################################################
LOG_DIR=".log/role=mechanic/skill=git.repo.test"

######################################################################
# parse arguments
######################################################################
WHAT=""
WHEN=""

while [[ $# -gt 0 ]]; do
  case $1 in
    # rhachet passes these - ignore them
    --skill|--repo|--role)
      shift 2
      ;;
    --what)
      WHAT="$2"
      shift 2
      ;;
    --when)
      WHEN="$2"
      shift 2
      ;;
    --help|-h)
      echo "usage: git.repo.test.sh --what <lint> [--when <context>]"
      echo ""
      echo "run repo tests with turtle vibes summary and log capture"
      echo ""
      echo "options:"
      echo "  --what <type>    which test to run (required, only 'lint' supported)"
      echo "  --when <context> context hint (optional, for future use)"
      echo "  --help, -h       show this help"
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1"
      exit 2
      ;;
  esac
done

######################################################################
# validate arguments
######################################################################
if [[ -z "$WHAT" ]]; then
  print_turtle_header "bummer dude..."
  print_tree_start "git.repo.test"
  echo "   └─ error: --what is required"
  echo ""
  echo "usage: git.repo.test.sh --what lint"
  exit 2
fi

if [[ "$WHAT" != "lint" ]]; then
  print_turtle_header "bummer dude..."
  print_tree_start "git.repo.test --what $WHAT"
  echo "   └─ error: only 'lint' is supported (got '$WHAT')"
  exit 2
fi

######################################################################
# validate git repo context
######################################################################
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  print_turtle_header "bummer dude..."
  print_tree_start "git.repo.test --what $WHAT"
  echo "   └─ error: not in a git repository"
  exit 2
fi

REPO_ROOT=$(git rev-parse --show-toplevel)

######################################################################
# validate package.json
######################################################################
if [[ ! -f "$REPO_ROOT/package.json" ]]; then
  print_turtle_header "bummer dude..."
  print_tree_start "git.repo.test --what $WHAT"
  echo "   └─ error: no package.json found"
  echo ""
  echo "this skill requires a node.js project with package.json"
  exit 2
fi

######################################################################
# findsert log directory and .gitignore
######################################################################
LOG_PATH="$REPO_ROOT/$LOG_DIR"
mkdir -p "$LOG_PATH"

GITIGNORE_PATH="$LOG_PATH/.gitignore"
if [[ ! -f "$GITIGNORE_PATH" ]]; then
  echo "# auto-generated by git.repo.test skill" > "$GITIGNORE_PATH"
  echo "*" >> "$GITIGNORE_PATH"
fi

######################################################################
# generate isotime filename (filesystem-safe: colons to hyphens)
######################################################################
ISOTIME=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
STDOUT_LOG="$LOG_PATH/${ISOTIME}.stdout.log"
STDERR_LOG="$LOG_PATH/${ISOTIME}.stderr.log"

# temp files for capture (only persist to log on error)
TEMP_STDOUT=$(mktemp)
TEMP_STDERR=$(mktemp)
trap "rm -f '$TEMP_STDOUT' '$TEMP_STDERR'" EXIT

######################################################################
# run npm test:lint
######################################################################
cd "$REPO_ROOT"

NPM_EXIT_CODE=0
npm run test:lint > "$TEMP_STDOUT" 2> "$TEMP_STDERR" || NPM_EXIT_CODE=$?

######################################################################
# parse defect count from output (only count ERRORS, not warnings)
######################################################################
ERROR_COUNT=0
if [[ -f "$TEMP_STDOUT" ]]; then
  # biome outputs "Found X errors" or "X error(s)"
  # eslint outputs "X problems (Y errors, Z warnings)" or "X errors"
  # we only want errors, not warnings

  # try biome format: "Found X errors"
  if grep -qiE "found [0-9]+ errors?" "$TEMP_STDOUT"; then
    ERROR_COUNT=$(grep -oiE "found [0-9]+ errors?" "$TEMP_STDOUT" | grep -oE "[0-9]+" | head -1 || echo "0")
  # try eslint format: "X problems (Y errors, Z warnings)"
  elif grep -qE "[0-9]+ errors?" "$TEMP_STDOUT"; then
    ERROR_COUNT=$(grep -oE "[0-9]+ errors?" "$TEMP_STDOUT" | head -1 | grep -oE "[0-9]+" || echo "0")
  fi
fi

# if npm failed but we found no errors, check if it's warnings-only
HAS_ERRORS=false
if [[ "$ERROR_COUNT" -gt 0 ]]; then
  HAS_ERRORS=true
elif [[ "$NPM_EXIT_CODE" -ne 0 ]]; then
  # npm failed but we found no errors - could be warnings-only or npm error
  # check if stderr has npm ERR! (real error) vs just lint warnings
  if grep -q "npm ERR!" "$TEMP_STDERR"; then
    HAS_ERRORS=true
    ERROR_COUNT="?"
  fi
  # else: warnings-only, treat as success
fi

######################################################################
# determine exit code and output
######################################################################

# relative log path for display
REL_STDOUT_LOG="$LOG_DIR/${ISOTIME}.stdout.log"
REL_STDERR_LOG="$LOG_DIR/${ISOTIME}.stderr.log"

if [[ "$HAS_ERRORS" == "false" ]]; then
  # lint passed (or warnings-only, which we treat as pass)
  print_turtle_header "cowabunga!"
  print_tree_start "git.repo.test --what $WHAT"
  echo "   └─ status: passed"
  # no log file on success - temp files cleaned up by trap
  exit 0
else
  # errors found - persist logs
  cp "$TEMP_STDOUT" "$STDOUT_LOG"
  cp "$TEMP_STDERR" "$STDERR_LOG"

  # check if this is a lint failure or npm error
  if grep -q "npm ERR!" "$TEMP_STDERR"; then
    # npm/command error (malfunction)
    print_turtle_header "bummer dude..."
    print_tree_start "git.repo.test --what $WHAT"
    print_tree_branch "status" "malfunction"
    echo "   └─ log: $REL_STDERR_LOG"
    echo ""
    echo "npm command failed. check the log for details."
    # output stderr to skill stderr for visibility
    cat "$TEMP_STDERR" >&2
    exit 1
  else
    # lint failed (constraint) - output to stderr so Claude Code shows it
    {
      print_turtle_header "bummer dude..."
      print_tree_start "git.repo.test --what $WHAT"
      print_tree_branch "status" "failed"
      print_tree_branch "defects" "$ERROR_COUNT"
      print_tree_branch "log" "$REL_STDOUT_LOG"
      echo "   └─ tip: try \`npm run fix\` then rerun, or Read the log path above for details"
    } >&2
    exit 2
  fi
fi
